### ISSUE TITLE
Create svg draft

### ISSUE THREAD

**Issue by TheJJ** [frickler01/openage-design#3]
Awesome work!

So far, I like `raw_02` `17` and `18` best. On `raw_05`, the top left sketch is also great, would make a nice icon if the `open` was written somewhere as well.

The `17` and `18` ideas are probably good as bigger logos/banners. Wheee, some artwork, finally :grin:

**Comment by fricklerhandwerk** [comment]
Thanks for the feedback!
I've done another take on the helmet theme in `43` and `47` as well as some experiments with typography, playing with tiles. `55` is an attempt to bring some of that together, though readability isn't great at small sizes. Typo is more like an ornament here.
I still can't decide whether to take a more abstract/modern path or copy the historic theme of the original.
Maybe you guys take another look at it and help me with that one.

**Comment by fricklerhandwerk** [comment]
Since there were no more suggestions, I've made some SVGs I considered worthwhile.
